fos_rest:
  routing_loader:
    include_format: false
  view:
    view_response_listener: true
  format_listener:
    rules:
      - { path: '^/api', priorities: ['json'], fallback_format: 'html' }
      - { path: '^/blog', priorities: ['html'] }
  body_converter:
    enabled: true
  serializer:
    serialize_null:  true