version: '3.4'
services:
  mysql:
    image: mysql:5.7
    command: --sql_mode=""
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: doctissimo
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "33060:3306"

  php:
    volumes:
      - ./:/var/www/html:rw,cached
    build:
      context: .
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
